# Code

In [43]:
import pandas as pd
from numpy import *
from math import sqrt
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

In [2]:
def hitung_jarak(data1, data2):
    selisih1 = data1['SepalLengthCm'] - data2['SepalLengthCm']
    selisih2 = data1['SepalWidthCm'] - data2['SepalWidthCm']
    selisih3 = data1['PetalLengthCm'] - data2['PetalLengthCm']
    selisih4 = data1['PetalWidthCm'] - data2['PetalWidthCm']
#     total = 0
#     for i in(0, self.__n_attr):
#         total += pow(data1[i] - data2[i], 2)
    total = selisih1*selisih1 + selisih2*selisih2 + selisih3*selisih3 + selisih4*selisih4;
    return sqrt(total)

In [3]:
def get_distance_matrix(data):
    for i in range(len(data_iris_temp)):
        for j in range(len(data_iris_temp)):
            dist_table[i][j] = hitung_jarak(data_iris_temp.loc[i], data_iris_temp.loc[j])

In [44]:
data_iris = pd.read_csv('Iris.csv')

data_iris_temp = data_iris.drop(["Species", "Id"], axis = 1)

iris_label = data_iris.values[:,-1]
species_encoder = LabelEncoder().fit(iris_label)

iris_label = species_encoder.transform(iris_label)

dist_table = [[]]
for i in range(150):
    for j in range(150):
        dist_table[i].append(1.0)
    dist_table.append([])
get_distance_matrix(data_iris_temp)
jumlah = 0
cnt = 0
for i in range(len(dist_table)):
    for j in range(len(dist_table[i])):
        jumlah += dist_table[i][j]
        cnt += 1
print(jumlah / cnt)
cluster = []
for i in range(150):
    cluster.append(-1)

2.5268107508366784


In [32]:
def get_cluster(index, eps):
    neighbour_list = []
    for i in range(len(dist_table[index])):
        if(dist_table[index][i] <= eps):
            neighbour_list.append(i)
    return neighbour_list

In [69]:
def dbscan_fit_predict(data, eps, minPts):
    cluster_index = 0
    #reset cluster value
    for i in range(150):
        cluster[i] = -1 
    for i in range(len(dist_table)):
        neighbour_list = get_cluster(i, eps)
        if(len(neighbour_list) >= minPts):
            if(cluster[i] == -1):
                
                for j in neighbour_list:
                    cluster[j] = cluster_index
                cluster_index += 1

# Contoh pemakaian

In [70]:
dbscan_iris = dbscan_fit_predict(data_iris_temp, 2.6, 5)
print(cluster)
array_cluster = [i for i in range(150)]
for i in range(len(cluster)):
    if(cluster[i] != -1):
        array_cluster[i] = cluster[i]

mat = confusion_matrix(array_cluster, iris_label)
print(mat)
purity = float(mat[0].max() + mat[1].max() + mat[2].max()) / float(mat.sum())
purity

[0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2]
[[26  0  0]
 [ 0  2 34]
 [24 48 16]]


0.72